# Generated by Django 4.0.6 on 2022-11-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('bookName', models.CharField(max_length=100)),
                ('date', models.DateTimeField(null=True)),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('date', models.FloatField()),
                ('word', models.CharField(max_length=100)),
                ('correctness', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MissingWord',
            fields=[
                ('word', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=20)),
                ('lastUpdate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=100)),
                ('meanings', models.CharField(max_length=400)),
                ('synonyms', models.CharField(max_length=400)),
                ('antonyms', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='WordPronounce',
            fields=[
                ('word', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100, null=True)),
                ('soundmark', models.CharField(max_length=100, null=True)),
                ('data', models.BinaryField(null=True)),
            ],
        ),
    ]
