# Generated by Django 4.0.6 on 2022-11-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingword',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordpronounce',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missingword',
            name='word',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wordpronounce',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
