# Generated by Django 4.0.6 on 2022-11-25 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_missingword_id_wordpronounce_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('bookName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GlossaryWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('addDate', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.glossarybooks')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('defaultBookName', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Glossary',
        ),
    ]
