# Generated by Django 4.0.6 on 2022-11-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_glossarybooks_glossarywords_userinfo_delete_glossary'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossarybooks',
            name='isDefault',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
