# Generated by Django 4.0.6 on 2022-11-25 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_glossarybooks_isdefault'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossarywords',
            name='addDate',
        ),
    ]
