# Generated by Django 4.0.6 on 2022-11-25 03:11

from django.db import migrations, models
from datetime import datetime 

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_glossarywords_adddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossarybooks',
            name='isDefault',
        ),
        migrations.AddField(
            model_name='glossarywords',
            name='addDate',
            field=models.DateTimeField(default=datetime.now()),
            preserve_default=False,
        ),
    ]
