# Generated by Django 4.0.6 on 2022-11-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_glossarybooks_isdefault_glossarywords_adddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossarywords',
            name='addDate',
            field=models.DateTimeField(null=True),
        ),
    ]
