# Generated by Django 4.0.6 on 2022-11-25 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_userinfo_id_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='defaultBookName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.glossarybooks'),
        ),
    ]
