# Generated by Django 4.1.4 on 2022-12-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userinfo_defaultbookname'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceList',
            fields=[
                ('source', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
