# Generated by Django 4.1.4 on 2022-12-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sourcelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceList',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='detailSouces',
            field=models.CharField(default='dictionaryapi,googleCN,ecdict', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='preferrdLanguage',
            field=models.CharField(default='CN', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='searchSource',
            field=models.CharField(default='ecdict', max_length=100),
            preserve_default=False,
        ),
    ]
