# Generated by Django 4.1.4 on 2022-12-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_sourcelist_userinfo_detailsouces_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='preferrdLanguage',
            new_name='language',
        ),
    ]
