# Generated by Django 4.1.4 on 2022-12-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_preferrdlanguage_userinfo_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worddefinition',
            name='antonyms',
        ),
        migrations.RemoveField(
            model_name='worddefinition',
            name='synonyms',
        ),
        migrations.AddField(
            model_name='missingword',
            name='language',
            field=models.CharField(default='CN', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='language',
            field=models.CharField(default='CN', max_length=10),
            preserve_default=False,
        ),
    ]
