# Generated by Django 4.1.4 on 2022-12-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_worddefinition_antonyms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='detailSouces',
            new_name='definitionSources',
        ),
    ]
