# Generated by Django 4.1.4 on 2022-12-24 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_detailsouces_userinfo_definitionsources'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='defaultExerciseBook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_defaultExerciseBook', to='api.glossarybooks'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='defaultBookName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_defaultBookName', to='api.glossarybooks'),
        ),
    ]
