# Generated by Django 4.1.4 on 2022-12-26 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_history_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='defaultBookName',
            new_name='glossaryBook',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='defaultExerciseBook',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='exerciseBook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_exerciseBook', to='api.glossarybooks'),
        ),
    ]
