# Generated by Django 4.1.4 on 2023-01-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_wordpronounce_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.BigIntegerField(),
        ),
    ]
