# Generated by Django 4.1.4 on 2023-01-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='uuid',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
