# Generated by Django 4.1.4 on 2023-03-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_history_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=400)),
            ],
        ),
    ]
